### ISSUE TITLE
按钮高亮可以通过重写set方法解决

### ISSUE THREAD

**Issue by devtofu** [NoCodeNoWife/LLRiseTabBar-iOS#1]
![image](https://cloud.githubusercontent.com/assets/12134966/10629799/946dcef8-7804-11e5-8c14-819fafabcf4f.png)
#### 在 `LLTabBarItem.m` 中加入以下代码就可以解决

``` objective-c
/**
 *  复写系统的高量实现，禁止按钮高亮
 *  此函数里不用写任何代码
 */
- (void)setHighlighted:(BOOL)highlighted{
  // do not anything  
}
```

**Comment by meilbn** [comment]
@devtofu 
搜噶，没想到，的确可行！谢谢！

**Comment by meilbn** [comment]
不用重写这个方法也可以： b5f76e80838f88b1bf09fc6fc4e4bd77d43e2940
