### ISSUE TITLE
How to Use it ?

### ISSUE THREAD

**Issue by subhash08** [NoCodeNoWife/LLRiseTabBar-iOS#3]
Can you please add some more detail in `readme`, like some code that show how to use it.
please also add a storyboard example. If possible then add cocoaPods support.

**Comment by meilbn** [comment]
@subhash08 
This Project is fully custom, If you want to use system UITabBar and CocoaPods, I'll recommend you to use [This Project](https://github.com/ChenYilong/CYLTabBarController).

**Comment by subhash08** [comment]
Thanks for the response @meilbn .
one more issue, `How to increase height of LLRiseTabBar.`
urgently need solution on Height issue.

**Comment by subhash08** [comment]
issue is solved @meilbn  thanks for this highly customisable control.

**Comment by meilbn** [comment]
@subhash08 You are welcome!
