### ISSUE TITLE
怎么实现点击中间的+号出现页面的切换呢？

### ISSUE THREAD

**Issue by hllGitHub** [NoCodeNoWife/LLRiseTabBar-iOS#5]
或者说，点击+号跟点击其他tabbaItem一样，切换到另外一个视图控制器上，请问怎么才能更好的实现呢？

**Comment by meilbn** [comment]
你的意思是想样式还是那种中间按钮凸起，然后点击是一个 UIViewController 是吧？那就是类似普通的 UITabBar 了，中间按钮也代表一个 UIViewController，点击加号，设置一下 UITabBar 的 selectedIndex 就可以了

**Comment by hllGitHub** [comment]
了解，已经搞定了！谢谢了
