### ISSUE TITLE
tabbar 显示问题

### ISSUE THREAD

**Issue by indenpendman** [NoCodeNoWife/LLRiseTabBar-iOS#6]
第二级视图不显示TABBAR 第三级视图就不能显示出来了。

**Comment by meilbn** [comment]
什么意思？能上张截图吗？

**Comment by indenpendman** [comment]
A,B,C三个视图控制器 ，A->B->C   ，A是根视图控制器，底部的tabBar 肯定是显示的，
现在我先从A PUSH 到B ，B视图底部不需要显示tabBar， B.hidesBottomBarWhenPushed = YES; 
然后从B push到C视图控制器， C 需要显示底部tabBar,      现在C.hidesBottomBarWhenPushed = NO; 就不起作用了。
需求就是任何视图控制器可以显示 或者隐藏底部的tabBar.

**Comment by meilbn** [comment]
我是添加到系统的 UITabBar 上的，要是系统的 tabBar 是能够显示的话，自定义的视图也是会显示出来的。我找个时间试试看。

**Comment by meilbn** [comment]
不好意思，现在才想起来测试一下。
发现系统的 Tab Bar 就是出不来的。
所以，正常。
